config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  resources :goals
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  body       :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  priv       :boolean
#  status     :string
#

class Goal < ActiveRecord::Base
  validates_presence_of :user, :body
  validates :priv, :inclusion => {:in => [true, false]}
  validates :status, :inclusion => {:in => ["Complete", "Incomplete"]}
  after_initialize :ensure_status

  belongs_to :user

  def ensure_status
    self.status ||= "Incomplete"
  end

  # def priv=(arg)
  #   puts arg
  #   @priv = 't' if arg == "true"
  #   @priv = 'f' if arg == "false"
  # end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  has_many :goals

  before_validation :ensure_session_token

  attr_reader :password

  def password=(password)
    @password = "*" * password.length
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return user if user && user.is_password?(password)
    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def ensure_logged_in
    redirect_to new_session_url unless logged_in?
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :ensure_logged_in

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    if @goal.save
      redirect_to @goal
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    if @goal.destroy
      redirect_to current_user
    else
      flash[:errors] = ["No such goal"]
      redirect_to current_user
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to @goal
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end


  def show
    @goal = Goal.find(params[:id])
    unless @goal.user == current_user
      redirect_to current_user
    end
  end

  private

  def goal_params
    params.require(:goal).permit(:body, :user_id, :priv, :status)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username],params[:user][:password])
    if @user
      login!(@user)
      redirect_to @user
    else
      @user = User.new(username: params[:user][:username])
      flash.now[:errors] = ["Login failed"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_logged_in, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      login!(@user)
      redirect_to @user
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<form action="<%= goal_url(@goal) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">

  <input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

  <input type="hidden" name="goal[user_id]" value="<%= current_user.id %>">

  <label>Body
    <input type="text" name="goal[body]" value="<%= @goal.body %>"
        id="body">
  </label>
  <br>

  <label>Private
    <input type="radio" name="goal[priv]" value="true" id="priv"></label>
  <label>Public
    <input type="radio" name="goal[priv]" value="false" id="pub"></label>

  <input type="submit" value="Edit Goal">
</form>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<form action="<%= goals_url %>" method="POST">
  <input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

  <input type="hidden" name="goal[user_id]" value="<%= current_user.id %>">

  <label>Body
    <input type="text" name="goal[body]" value="<%= @goal.body %>"
        id="body">
  </label>
  <br>

  <label>Private
    <input type="radio" name="goal[priv]" value="true" id="priv"></label>
  <label>Public
    <input type="radio" name="goal[priv]" value="false" id="pub"></label>

  <input type="submit" value="Create Goal">
</form>

app/views/goals/show.html.erb
<h1>Goal</h1>

<%= @goal.body %>
<%= "Private" if @goal.priv %>
<%= "Public" unless @goal.priv %>
<br>
<%= link_to "Edit Goal", edit_goal_url(@goal) %>
<br>
<%= button_to "Delete Goal", goal_url(@goal), method: :delete %>
<%= @goal.status %>
<% if @goal.status == "Incomplete" %>
  <form action="<%= goal_url(@goal) %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">

    <input type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">

    <input type="hidden" name="goal[status]" value="Complete">
    <input type="submit" value="Goal Complete">
  </form>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalSetter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/header' %>
<%= render 'shared/flash' %>

<%= yield %>

</body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

app/views/shared/_header.html.erb
<% if current_user %>
  <%= button_to "Logout", session_url, method: :delete %>
<% else %>
  <%= button_to "Login", new_session_url %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<form action="<%= users_url %>" method="POST">
  <input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

  <label>Username
    <input type="text" name="user[username]" value="<%= @user.username %>"
        id="username">
  </label>
  <br>

  <label>Password
    <input type="password" name="user[password]" id="password">
  </label>

  <input type="submit" value="Create User">
</form>

app/views/users/show.html.erb
<h1><%= "Welcome, #{@user.username}" %></h1>

<ul>
  <% @user.goals.each do |goal| %>
    <% if current_user == @user %>
      <li><%= goal.body %></li>
    <% elsif !goal.priv %>
      <li><%= goal.body %></li>
    <% end %>
  <% end %>
</ul>